package com.es.assurance.model;
// Generated 4 nov. 2015 21:54:52 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Adresses generated by hbm2java
 */
public class Adresses implements java.io.Serializable {

	private Integer id;
	private Rues rues;
	private String no;
	private Set<Entreprises> entrepriseses = new HashSet<Entreprises>(0);
	private Set<Clients> clientses = new HashSet<Clients>(0);

	public Adresses() {
	}

	public Adresses(Rues rues, String no) {
		this.rues = rues;
		this.no = no;
	}

	public Adresses(Rues rues, String no, Set<Entreprises> entrepriseses, Set<Clients> clientses) {
		this.rues = rues;
		this.no = no;
		this.entrepriseses = entrepriseses;
		this.clientses = clientses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Rues getRues() {
		return this.rues;
	}

	public void setRues(Rues rues) {
		this.rues = rues;
	}

	public String getNo() {
		return this.no;
	}

	public void setNo(String no) {
		this.no = no;
	}

	public Set<Entreprises> getEntrepriseses() {
		return this.entrepriseses;
	}

	public void setEntrepriseses(Set<Entreprises> entrepriseses) {
		this.entrepriseses = entrepriseses;
	}

	public Set<Clients> getClientses() {
		return this.clientses;
	}

	public void setClientses(Set<Clients> clientses) {
		this.clientses = clientses;
	}

}
