package com.es.assurance.model;
// Generated 4 nov. 2015 21:54:52 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AssurancesAnnee generated by hbm2java
 */
public class AssurancesAnnee implements java.io.Serializable {

	private Integer id;
	private Bases bases;
	private Complementaires complementaires;
	private Date annee;
	private float prix;
	private Set<AssuranceAnneeListeMedicament> assuranceAnneeListeMedicaments = new HashSet<AssuranceAnneeListeMedicament>(
			0);
	private Set<Assurances> assuranceses = new HashSet<Assurances>(0);

	public AssurancesAnnee() {
	}

	public AssurancesAnnee(Date annee, float prix) {
		this.annee = annee;
		this.prix = prix;
	}

	public AssurancesAnnee(Bases bases, Complementaires complementaires, Date annee, float prix,
			Set<AssuranceAnneeListeMedicament> assuranceAnneeListeMedicaments, Set<Assurances> assuranceses) {
		this.bases = bases;
		this.complementaires = complementaires;
		this.annee = annee;
		this.prix = prix;
		this.assuranceAnneeListeMedicaments = assuranceAnneeListeMedicaments;
		this.assuranceses = assuranceses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Bases getBases() {
		return this.bases;
	}

	public void setBases(Bases bases) {
		this.bases = bases;
	}

	public Complementaires getComplementaires() {
		return this.complementaires;
	}

	public void setComplementaires(Complementaires complementaires) {
		this.complementaires = complementaires;
	}

	public Date getAnnee() {
		return this.annee;
	}

	public void setAnnee(Date annee) {
		this.annee = annee;
	}

	public float getPrix() {
		return this.prix;
	}

	public void setPrix(float prix) {
		this.prix = prix;
	}

	public Set<AssuranceAnneeListeMedicament> getAssuranceAnneeListeMedicaments() {
		return this.assuranceAnneeListeMedicaments;
	}

	public void setAssuranceAnneeListeMedicaments(Set<AssuranceAnneeListeMedicament> assuranceAnneeListeMedicaments) {
		this.assuranceAnneeListeMedicaments = assuranceAnneeListeMedicaments;
	}

	public Set<Assurances> getAssuranceses() {
		return this.assuranceses;
	}

	public void setAssuranceses(Set<Assurances> assuranceses) {
		this.assuranceses = assuranceses;
	}

}
