package com.es.assurance.model;
// Generated 4 nov. 2015 21:54:52 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Clients generated by hbm2java
 */
public class Clients implements java.io.Serializable {

	private Integer id;
	private Adresses adresses;
	private Entreprises entreprises;
	private String nom;
	private String prenom;
	private String telephone;
	private String email;
	private Date anniversaire;
	private Set<FacturesRembourcement> facturesRembourcements = new HashSet<FacturesRembourcement>(0);
	private Set<PolicesAssurance> policesAssurances = new HashSet<PolicesAssurance>(0);

	public Clients() {
	}

	public Clients(Adresses adresses, String nom, String prenom, String telephone, Date anniversaire) {
		this.adresses = adresses;
		this.nom = nom;
		this.prenom = prenom;
		this.telephone = telephone;
		this.anniversaire = anniversaire;
	}

	public Clients(Adresses adresses, Entreprises entreprises, String nom, String prenom, String telephone,
			String email, Date anniversaire, Set<FacturesRembourcement> facturesRembourcements,
			Set<PolicesAssurance> policesAssurances) {
		this.adresses = adresses;
		this.entreprises = entreprises;
		this.nom = nom;
		this.prenom = prenom;
		this.telephone = telephone;
		this.email = email;
		this.anniversaire = anniversaire;
		this.facturesRembourcements = facturesRembourcements;
		this.policesAssurances = policesAssurances;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Adresses getAdresses() {
		return this.adresses;
	}

	public void setAdresses(Adresses adresses) {
		this.adresses = adresses;
	}

	public Entreprises getEntreprises() {
		return this.entreprises;
	}

	public void setEntreprises(Entreprises entreprises) {
		this.entreprises = entreprises;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Date getAnniversaire() {
		return this.anniversaire;
	}

	public void setAnniversaire(Date anniversaire) {
		this.anniversaire = anniversaire;
	}

	public Set<FacturesRembourcement> getFacturesRembourcements() {
		return this.facturesRembourcements;
	}

	public void setFacturesRembourcements(Set<FacturesRembourcement> facturesRembourcements) {
		this.facturesRembourcements = facturesRembourcements;
	}

	public Set<PolicesAssurance> getPolicesAssurances() {
		return this.policesAssurances;
	}

	public void setPolicesAssurances(Set<PolicesAssurance> policesAssurances) {
		this.policesAssurances = policesAssurances;
	}

}
