package com.es.assurance.model;
// Generated 12 nov. 2015 20:05:27 by Hibernate Tools 4.3.1.Final

/**
 * DossiersMedical generated by hbm2java
 */
public class DossiersMedical implements java.io.Serializable {

	private Integer id;
	private Clients clients;
	private Frais frais;
	private String nom;
	private String description;

	public DossiersMedical() {
	}

	public DossiersMedical(Clients clients, String nom, String description) {
		this.clients = clients;
		this.nom = nom;
		this.description = description;
	}

	public DossiersMedical(Clients clients, Frais frais, String nom, String description) {
		this.clients = clients;
		this.frais = frais;
		this.nom = nom;
		this.description = description;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Clients getClients() {
		return this.clients;
	}

	public void setClients(Clients clients) {
		this.clients = clients;
	}

	public Frais getFrais() {
		return this.frais;
	}

	public void setFrais(Frais frais) {
		this.frais = frais;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
