package com.es.assurance.model;
// Generated 8 nov. 2015 22:21:35 by Hibernate Tools 4.3.1.Final

/**
 * EntrepriseMedecin generated by hbm2java
 */
public class EntrepriseMedecin implements java.io.Serializable {

	private Integer id;
	private Entreprises entreprises;
	private Medecins medecins;

	public EntrepriseMedecin() {
	}

	public EntrepriseMedecin(Entreprises entreprises, Medecins medecins) {
		this.entreprises = entreprises;
		this.medecins = medecins;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Entreprises getEntreprises() {
		return this.entreprises;
	}

	public void setEntreprises(Entreprises entreprises) {
		this.entreprises = entreprises;
	}

	public Medecins getMedecins() {
		return this.medecins;
	}

	public void setMedecins(Medecins medecins) {
		this.medecins = medecins;
	}

}
