package com.es.assurance.model;
// Generated 8 nov. 2015 22:21:35 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Entreprises generated by hbm2java
 */
public class Entreprises implements java.io.Serializable {

	private Integer id;
	private Adresses adresses;
	private String nom;
	private String compteBancaire;
	private Set<Clients> clientses = new HashSet<Clients>(0);
	private Set<EntrepriseMedecin> entrepriseMedecins = new HashSet<EntrepriseMedecin>(0);
	private Set<FacturesRembourcement> facturesRembourcements = new HashSet<FacturesRembourcement>(0);

	public Entreprises() {
	}

	public Entreprises(Adresses adresses, String nom) {
		this.adresses = adresses;
		this.nom = nom;
	}

	public Entreprises(Adresses adresses, String nom, String compteBancaire, Set<Clients> clientses,
			Set<EntrepriseMedecin> entrepriseMedecins, Set<FacturesRembourcement> facturesRembourcements) {
		this.adresses = adresses;
		this.nom = nom;
		this.compteBancaire = compteBancaire;
		this.clientses = clientses;
		this.entrepriseMedecins = entrepriseMedecins;
		this.facturesRembourcements = facturesRembourcements;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Adresses getAdresses() {
		return this.adresses;
	}

	public void setAdresses(Adresses adresses) {
		this.adresses = adresses;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getCompteBancaire() {
		return this.compteBancaire;
	}

	public void setCompteBancaire(String compteBancaire) {
		this.compteBancaire = compteBancaire;
	}

	public Set<Clients> getClientses() {
		return this.clientses;
	}

	public void setClientses(Set<Clients> clientses) {
		this.clientses = clientses;
	}

	public Set<EntrepriseMedecin> getEntrepriseMedecins() {
		return this.entrepriseMedecins;
	}

	public void setEntrepriseMedecins(Set<EntrepriseMedecin> entrepriseMedecins) {
		this.entrepriseMedecins = entrepriseMedecins;
	}

	public Set<FacturesRembourcement> getFacturesRembourcements() {
		return this.facturesRembourcements;
	}

	public void setFacturesRembourcements(Set<FacturesRembourcement> facturesRembourcements) {
		this.facturesRembourcements = facturesRembourcements;
	}

}
