package com.es.assurance.model;
// Generated 8 nov. 2015 22:21:35 by Hibernate Tools 4.3.1.Final

/**
 * Facturations generated by hbm2java
 */
public class Facturations implements java.io.Serializable {

	private int id;
	private PolicesAssurance policesAssurance;
	private float montant;
	private String dateDebut;
	private String dateEcheance;
	private String datePayement;

	public Facturations() {
	}

	public Facturations(int id, PolicesAssurance policesAssurance, float montant, String dateDebut,
			String dateEcheance) {
		this.id = id;
		this.policesAssurance = policesAssurance;
		this.montant = montant;
		this.dateDebut = dateDebut;
		this.dateEcheance = dateEcheance;
	}

	public Facturations(int id, PolicesAssurance policesAssurance, float montant, String dateDebut, String dateEcheance,
			String datePayement) {
		this.id = id;
		this.policesAssurance = policesAssurance;
		this.montant = montant;
		this.dateDebut = dateDebut;
		this.dateEcheance = dateEcheance;
		this.datePayement = datePayement;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public PolicesAssurance getPolicesAssurance() {
		return this.policesAssurance;
	}

	public void setPolicesAssurance(PolicesAssurance policesAssurance) {
		this.policesAssurance = policesAssurance;
	}

	public float getMontant() {
		return this.montant;
	}

	public void setMontant(float montant) {
		this.montant = montant;
	}

	public String getDateDebut() {
		return this.dateDebut;
	}

	public void setDateDebut(String dateDebut) {
		this.dateDebut = dateDebut;
	}

	public String getDateEcheance() {
		return this.dateEcheance;
	}

	public void setDateEcheance(String dateEcheance) {
		this.dateEcheance = dateEcheance;
	}

	public String getDatePayement() {
		return this.datePayement;
	}

	public void setDatePayement(String datePayement) {
		this.datePayement = datePayement;
	}

}
