package com.es.assurance.model;
// Generated 8 nov. 2015 22:21:35 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Familles generated by hbm2java
 */
public class Familles implements java.io.Serializable {

	private Integer id;
	private Clients clients;
	private String nom;
	private Set<PolicesAssurance> policesAssurances = new HashSet<PolicesAssurance>(0);

	public Familles() {
	}

	public Familles(Clients clients, String nom) {
		this.clients = clients;
		this.nom = nom;
	}

	public Familles(Clients clients, String nom, Set<PolicesAssurance> policesAssurances) {
		this.clients = clients;
		this.nom = nom;
		this.policesAssurances = policesAssurances;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Clients getClients() {
		return this.clients;
	}

	public void setClients(Clients clients) {
		this.clients = clients;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public Set<PolicesAssurance> getPolicesAssurances() {
		return this.policesAssurances;
	}

	public void setPolicesAssurances(Set<PolicesAssurance> policesAssurances) {
		this.policesAssurances = policesAssurances;
	}

}
