package com.es.assurance.model;
// Generated 8 nov. 2015 22:21:35 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Frais generated by hbm2java
 */
public class Frais implements java.io.Serializable {

	private Integer id;
	private Medecins medecins;
	private PolicesAssurance policesAssurance;
	private TypesFrais typesFrais;
	private String description;
	private byte[] scan;
	private boolean causeAccident;
	private float prix;
	private Date date;
	private Date dateFin;
	private Set<Couvertures> couvertureses = new HashSet<Couvertures>(0);
	private Set<Rembourcements> rembourcementses = new HashSet<Rembourcements>(0);
	private Set<DossiersMedical> dossiersMedicals = new HashSet<DossiersMedical>(0);
	private Set<Prescris> prescrises = new HashSet<Prescris>(0);

	public Frais() {
	}

	public Frais(PolicesAssurance policesAssurance, TypesFrais typesFrais, String description, byte[] scan,
			boolean causeAccident, float prix, Date date) {
		this.policesAssurance = policesAssurance;
		this.typesFrais = typesFrais;
		this.description = description;
		this.scan = scan;
		this.causeAccident = causeAccident;
		this.prix = prix;
		this.date = date;
	}

	public Frais(Medecins medecins, PolicesAssurance policesAssurance, TypesFrais typesFrais, String description,
			byte[] scan, boolean causeAccident, float prix, Date date, Date dateFin, Set<Couvertures> couvertureses,
			Set<Rembourcements> rembourcementses, Set<DossiersMedical> dossiersMedicals, Set<Prescris> prescrises) {
		this.medecins = medecins;
		this.policesAssurance = policesAssurance;
		this.typesFrais = typesFrais;
		this.description = description;
		this.scan = scan;
		this.causeAccident = causeAccident;
		this.prix = prix;
		this.date = date;
		this.dateFin = dateFin;
		this.couvertureses = couvertureses;
		this.rembourcementses = rembourcementses;
		this.dossiersMedicals = dossiersMedicals;
		this.prescrises = prescrises;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Medecins getMedecins() {
		return this.medecins;
	}

	public void setMedecins(Medecins medecins) {
		this.medecins = medecins;
	}

	public PolicesAssurance getPolicesAssurance() {
		return this.policesAssurance;
	}

	public void setPolicesAssurance(PolicesAssurance policesAssurance) {
		this.policesAssurance = policesAssurance;
	}

	public TypesFrais getTypesFrais() {
		return this.typesFrais;
	}

	public void setTypesFrais(TypesFrais typesFrais) {
		this.typesFrais = typesFrais;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public byte[] getScan() {
		return this.scan;
	}

	public void setScan(byte[] scan) {
		this.scan = scan;
	}

	public boolean isCauseAccident() {
		return this.causeAccident;
	}

	public void setCauseAccident(boolean causeAccident) {
		this.causeAccident = causeAccident;
	}

	public float getPrix() {
		return this.prix;
	}

	public void setPrix(float prix) {
		this.prix = prix;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public Date getDateFin() {
		return this.dateFin;
	}

	public void setDateFin(Date dateFin) {
		this.dateFin = dateFin;
	}

	public Set<Couvertures> getCouvertureses() {
		return this.couvertureses;
	}

	public void setCouvertureses(Set<Couvertures> couvertureses) {
		this.couvertureses = couvertureses;
	}

	public Set<Rembourcements> getRembourcementses() {
		return this.rembourcementses;
	}

	public void setRembourcementses(Set<Rembourcements> rembourcementses) {
		this.rembourcementses = rembourcementses;
	}

	public Set<DossiersMedical> getDossiersMedicals() {
		return this.dossiersMedicals;
	}

	public void setDossiersMedicals(Set<DossiersMedical> dossiersMedicals) {
		this.dossiersMedicals = dossiersMedicals;
	}

	public Set<Prescris> getPrescrises() {
		return this.prescrises;
	}

	public void setPrescrises(Set<Prescris> prescrises) {
		this.prescrises = prescrises;
	}

}
