package com.es.assurance.model;
// Generated 8 nov. 2015 22:21:35 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ListesMedicament generated by hbm2java
 */
public class ListesMedicament implements java.io.Serializable {

	private Integer id;
	private String description;
	private Date anneeDebut;
	private Date anneeFin;
	private Set<AssuranceAnneeListeMedicament> assuranceAnneeListeMedicaments = new HashSet<AssuranceAnneeListeMedicament>(
			0);
	private Set<MedicamentListeMedicament> medicamentListeMedicaments = new HashSet<MedicamentListeMedicament>(0);

	public ListesMedicament() {
	}

	public ListesMedicament(String description, Date anneeDebut) {
		this.description = description;
		this.anneeDebut = anneeDebut;
	}

	public ListesMedicament(String description, Date anneeDebut, Date anneeFin,
			Set<AssuranceAnneeListeMedicament> assuranceAnneeListeMedicaments,
			Set<MedicamentListeMedicament> medicamentListeMedicaments) {
		this.description = description;
		this.anneeDebut = anneeDebut;
		this.anneeFin = anneeFin;
		this.assuranceAnneeListeMedicaments = assuranceAnneeListeMedicaments;
		this.medicamentListeMedicaments = medicamentListeMedicaments;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getAnneeDebut() {
		return this.anneeDebut;
	}

	public void setAnneeDebut(Date anneeDebut) {
		this.anneeDebut = anneeDebut;
	}

	public Date getAnneeFin() {
		return this.anneeFin;
	}

	public void setAnneeFin(Date anneeFin) {
		this.anneeFin = anneeFin;
	}

	public Set<AssuranceAnneeListeMedicament> getAssuranceAnneeListeMedicaments() {
		return this.assuranceAnneeListeMedicaments;
	}

	public void setAssuranceAnneeListeMedicaments(Set<AssuranceAnneeListeMedicament> assuranceAnneeListeMedicaments) {
		this.assuranceAnneeListeMedicaments = assuranceAnneeListeMedicaments;
	}

	public Set<MedicamentListeMedicament> getMedicamentListeMedicaments() {
		return this.medicamentListeMedicaments;
	}

	public void setMedicamentListeMedicaments(Set<MedicamentListeMedicament> medicamentListeMedicaments) {
		this.medicamentListeMedicaments = medicamentListeMedicaments;
	}

}
