package com.es.assurance.model;
// Generated 8 nov. 2015 22:21:35 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Medicaments generated by hbm2java
 */
public class Medicaments implements java.io.Serializable {

	private Integer id;
	private String nom;
	private Set<Prescris> prescrises = new HashSet<Prescris>(0);
	private Set<MedicamentListeMedicament> medicamentListeMedicaments = new HashSet<MedicamentListeMedicament>(0);

	public Medicaments() {
	}

	public Medicaments(String nom) {
		this.nom = nom;
	}

	public Medicaments(String nom, Set<Prescris> prescrises,
			Set<MedicamentListeMedicament> medicamentListeMedicaments) {
		this.nom = nom;
		this.prescrises = prescrises;
		this.medicamentListeMedicaments = medicamentListeMedicaments;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public Set<Prescris> getPrescrises() {
		return this.prescrises;
	}

	public void setPrescrises(Set<Prescris> prescrises) {
		this.prescrises = prescrises;
	}

	public Set<MedicamentListeMedicament> getMedicamentListeMedicaments() {
		return this.medicamentListeMedicaments;
	}

	public void setMedicamentListeMedicaments(Set<MedicamentListeMedicament> medicamentListeMedicaments) {
		this.medicamentListeMedicaments = medicamentListeMedicaments;
	}

}
