package com.es.assurance.model;
// Generated 4 nov. 2015 21:54:52 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Npa generated by hbm2java
 */
public class Npa implements java.io.Serializable {

	private Integer id;
	private Villes villes;
	private String npa;
	private Set<Rues> rueses = new HashSet<Rues>(0);

	public Npa() {
	}

	public Npa(Villes villes, String npa) {
		this.villes = villes;
		this.npa = npa;
	}

	public Npa(Villes villes, String npa, Set<Rues> rueses) {
		this.villes = villes;
		this.npa = npa;
		this.rueses = rueses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Villes getVilles() {
		return this.villes;
	}

	public void setVilles(Villes villes) {
		this.villes = villes;
	}

	public String getNpa() {
		return this.npa;
	}

	public void setNpa(String npa) {
		this.npa = npa;
	}

	public Set<Rues> getRueses() {
		return this.rueses;
	}

	public void setRueses(Set<Rues> rueses) {
		this.rueses = rueses;
	}

}
