package com.es.assurance.model;
// Generated 8 nov. 2015 22:21:35 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PolicesAssurance generated by hbm2java
 */
public class PolicesAssurance implements java.io.Serializable {

	private Integer id;
	private Clients clients;
	private Familles familles;
	private TypesPersonne typesPersonne;
	private Date annee;
	private Date dateFin;
	private Set<Assurances> assuranceses = new HashSet<Assurances>(0);
	private Set<Facturations> facturationses = new HashSet<Facturations>(0);
	private Set<Frais> fraises = new HashSet<Frais>(0);

	public PolicesAssurance() {
	}

	public PolicesAssurance(Clients clients, TypesPersonne typesPersonne, Date annee) {
		this.clients = clients;
		this.typesPersonne = typesPersonne;
		this.annee = annee;
	}

	public PolicesAssurance(Clients clients, Familles familles, TypesPersonne typesPersonne, Date annee, Date dateFin,
			Set<Assurances> assuranceses, Set<Facturations> facturationses, Set<Frais> fraises) {
		this.clients = clients;
		this.familles = familles;
		this.typesPersonne = typesPersonne;
		this.annee = annee;
		this.dateFin = dateFin;
		this.assuranceses = assuranceses;
		this.facturationses = facturationses;
		this.fraises = fraises;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Clients getClients() {
		return this.clients;
	}

	public void setClients(Clients clients) {
		this.clients = clients;
	}

	public Familles getFamilles() {
		return this.familles;
	}

	public void setFamilles(Familles familles) {
		this.familles = familles;
	}

	public TypesPersonne getTypesPersonne() {
		return this.typesPersonne;
	}

	public void setTypesPersonne(TypesPersonne typesPersonne) {
		this.typesPersonne = typesPersonne;
	}

	public Date getAnnee() {
		return this.annee;
	}

	public void setAnnee(Date annee) {
		this.annee = annee;
	}

	public Date getDateFin() {
		return this.dateFin;
	}

	public void setDateFin(Date dateFin) {
		this.dateFin = dateFin;
	}

	public Set<Assurances> getAssuranceses() {
		return this.assuranceses;
	}

	public void setAssuranceses(Set<Assurances> assuranceses) {
		this.assuranceses = assuranceses;
	}

	public Set<Facturations> getFacturationses() {
		return this.facturationses;
	}

	public void setFacturationses(Set<Facturations> facturationses) {
		this.facturationses = facturationses;
	}

	public Set<Frais> getFraises() {
		return this.fraises;
	}

	public void setFraises(Set<Frais> fraises) {
		this.fraises = fraises;
	}

}
