package com.es.assurance.model;
// Generated 12 nov. 2015 20:05:27 by Hibernate Tools 4.3.1.Final

/**
 * Prescris generated by hbm2java
 */
public class Prescris implements java.io.Serializable {

	private Integer id;
	private Frais frais;
	private Medicaments medicaments;

	public Prescris() {
	}

	public Prescris(Frais frais, Medicaments medicaments) {
		this.frais = frais;
		this.medicaments = medicaments;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Frais getFrais() {
		return this.frais;
	}

	public void setFrais(Frais frais) {
		this.frais = frais;
	}

	public Medicaments getMedicaments() {
		return this.medicaments;
	}

	public void setMedicaments(Medicaments medicaments) {
		this.medicaments = medicaments;
	}

}
