package com.es.assurance.model;
// Generated 8 nov. 2015 22:21:35 by Hibernate Tools 4.3.1.Final

/**
 * Prescris generated by hbm2java
 */
public class Prescris implements java.io.Serializable {

	private int id;
	private Frais frais;
	private Medicaments medicaments;

	public Prescris() {
	}

	public Prescris(int id, Frais frais, Medicaments medicaments) {
		this.id = id;
		this.frais = frais;
		this.medicaments = medicaments;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Frais getFrais() {
		return this.frais;
	}

	public void setFrais(Frais frais) {
		this.frais = frais;
	}

	public Medicaments getMedicaments() {
		return this.medicaments;
	}

	public void setMedicaments(Medicaments medicaments) {
		this.medicaments = medicaments;
	}

}
