package com.es.assurance.model;
// Generated 8 nov. 2015 22:21:35 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Rembourcements generated by hbm2java
 */
public class Rembourcements implements java.io.Serializable {

	private Integer id;
	private Frais frais;
	private float prix;
	private Date date;
	private boolean quotePart;
	private Set<FacturesRembourcement> facturesRembourcements = new HashSet<FacturesRembourcement>(0);

	public Rembourcements() {
	}

	public Rembourcements(Frais frais, float prix, Date date, boolean quotePart) {
		this.frais = frais;
		this.prix = prix;
		this.date = date;
		this.quotePart = quotePart;
	}

	public Rembourcements(Frais frais, float prix, Date date, boolean quotePart,
			Set<FacturesRembourcement> facturesRembourcements) {
		this.frais = frais;
		this.prix = prix;
		this.date = date;
		this.quotePart = quotePart;
		this.facturesRembourcements = facturesRembourcements;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Frais getFrais() {
		return this.frais;
	}

	public void setFrais(Frais frais) {
		this.frais = frais;
	}

	public float getPrix() {
		return this.prix;
	}

	public void setPrix(float prix) {
		this.prix = prix;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public boolean isQuotePart() {
		return this.quotePart;
	}

	public void setQuotePart(boolean quotePart) {
		this.quotePart = quotePart;
	}

	public Set<FacturesRembourcement> getFacturesRembourcements() {
		return this.facturesRembourcements;
	}

	public void setFacturesRembourcements(Set<FacturesRembourcement> facturesRembourcements) {
		this.facturesRembourcements = facturesRembourcements;
	}

}
