package com.es.assurance.model;
// Generated 8 nov. 2015 22:21:35 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Rues generated by hbm2java
 */
public class Rues implements java.io.Serializable {

	private Integer id;
	private Npa npa;
	private String rue;
	private Set<Adresses> adresseses = new HashSet<Adresses>(0);

	public Rues() {
	}

	public Rues(Npa npa, String rue) {
		this.npa = npa;
		this.rue = rue;
	}

	public Rues(Npa npa, String rue, Set<Adresses> adresseses) {
		this.npa = npa;
		this.rue = rue;
		this.adresseses = adresseses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Npa getNpa() {
		return this.npa;
	}

	public void setNpa(Npa npa) {
		this.npa = npa;
	}

	public String getRue() {
		return this.rue;
	}

	public void setRue(String rue) {
		this.rue = rue;
	}

	public Set<Adresses> getAdresseses() {
		return this.adresseses;
	}

	public void setAdresseses(Set<Adresses> adresseses) {
		this.adresseses = adresseses;
	}

}
