package com.es.assurance.model;
// Generated 4 nov. 2015 21:54:52 by Hibernate Tools 4.3.1.Final

/**
 * TitreMedecin generated by hbm2java
 */
public class TitreMedecin implements java.io.Serializable {

	private Integer id;
	private Medecins medecins;
	private Titres titres;

	public TitreMedecin() {
	}

	public TitreMedecin(Medecins medecins, Titres titres) {
		this.medecins = medecins;
		this.titres = titres;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Medecins getMedecins() {
		return this.medecins;
	}

	public void setMedecins(Medecins medecins) {
		this.medecins = medecins;
	}

	public Titres getTitres() {
		return this.titres;
	}

	public void setTitres(Titres titres) {
		this.titres = titres;
	}

}
