package com.es.assurance.model;
// Generated 8 nov. 2015 22:21:35 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * TypesPersonne generated by hbm2java
 */
public class TypesPersonne implements java.io.Serializable {

	private Integer id;
	private String type;
	private Set<PolicesAssurance> policesAssurances = new HashSet<PolicesAssurance>(0);

	public TypesPersonne() {
	}

	public TypesPersonne(String type) {
		this.type = type;
	}

	public TypesPersonne(String type, Set<PolicesAssurance> policesAssurances) {
		this.type = type;
		this.policesAssurances = policesAssurances;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Set<PolicesAssurance> getPolicesAssurances() {
		return this.policesAssurances;
	}

	public void setPolicesAssurances(Set<PolicesAssurance> policesAssurances) {
		this.policesAssurances = policesAssurances;
	}

}
