package com.es.assurance.model;
// Generated 4 nov. 2015 21:54:52 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * TypesFrais generated by hbm2java
 */
public class TypesFrais implements java.io.Serializable {

	private Integer id;
	private String nom;
	private String description;
	private Set<Frais> fraises = new HashSet<Frais>(0);

	public TypesFrais() {
	}

	public TypesFrais(String nom, String description) {
		this.nom = nom;
		this.description = description;
	}

	public TypesFrais(String nom, String description, Set<Frais> fraises) {
		this.nom = nom;
		this.description = description;
		this.fraises = fraises;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<Frais> getFraises() {
		return this.fraises;
	}

	public void setFraises(Set<Frais> fraises) {
		this.fraises = fraises;
	}

}
