package com.es.assurance.model;
// Generated 4 nov. 2015 21:54:52 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Villes generated by hbm2java
 */
public class Villes implements java.io.Serializable {

	private Integer id;
	private String nom;
	private Set<Npa> npas = new HashSet<Npa>(0);

	public Villes() {
	}

	public Villes(String nom) {
		this.nom = nom;
	}

	public Villes(String nom, Set<Npa> npas) {
		this.nom = nom;
		this.npas = npas;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public Set<Npa> getNpas() {
		return this.npas;
	}

	public void setNpas(Set<Npa> npas) {
		this.npas = npas;
	}

}
